# Introduction to Numpy and Pandas

In [1]:
import numpy as np
import pandas as pd

Numpy provide N-Dimensional Arrays

In [5]:
oned_array = np.array([1, 2, 3, 4])

In [6]:
oned_array.shape

(4,)

In [32]:
print(oned_array)

[1 2 3 4]


In [33]:
twod_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [34]:
# find its dimensions
twod_array.shape

(3, 3)

In [42]:
# check its type
twod_array.dtype

dtype('int32')

In [35]:
print(twod_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
normal_2d_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [37]:
print(normal_2d_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


normal python lists can have multiple types

In [38]:
normal_2d_list = [[1, 2, 3], [4, "5", 6], [7, 8, 9]]

In [39]:
print(normal_2d_list)

[[1, 2, 3], [4, '5', 6], [7, 8, 9]]


But, numpy array elements need to have same type

In [40]:
np.array( [[1, 2, 3], [4, "5", 6], [7, 8, 9]])

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], 
      dtype='<U11')

In [41]:
twod_array.dtype

dtype('int32')