In [39]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [3]:
a = np.array([[1, 2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [17]:
b = np.array([10, 20]).reshape((2,1))
b

array([[10],
       [20]])

In [21]:
c = np.matmul(a, b)
c

array([[ 50],
       [110]])

In [11]:
tf_a = tf.placeholder(tf.int32, shape=(2, 2))
tf_a

<tf.Tensor 'Placeholder:0' shape=(2, 2) dtype=int32>

In [18]:
tf_b = tf.placeholder(tf.int32, shape=(2, 1))
tf_b

<tf.Tensor 'Placeholder_2:0' shape=(2, 1) dtype=int32>

In [31]:
tf_c = tf.matmul(a, b)
tf_c

<tf.Tensor 'MatMul_3:0' shape=(2, 1) dtype=int32>

In [32]:
tf_v = tf.Variable(0, dtype=tf.int32)

In [37]:
assign_op = tf_v.assign(tf_v + tf.reduce_sum(tf_c))

In [35]:
init_op = tf.global_variables_initializer()

In [38]:
with tf.Session() as sess:
    sess.run(init_op)
    sess.run(assign_op)
    results = sess.run([tf_c, tf_v], feed_dict={tf_a: a, tf_b: b})
    print(results)

[array([[ 50],
       [110]]), 160]


In [ ]:
v = tf.Variable

In [ ]:
v = tf.Variable